### PR TITLE
Update to Latest Zig

### PR DESCRIPTION
**Pull request by jcalabro**
Hi there! I track master zig in a bunch of my projects, and there have been a few changes since `master` on zap.

A more thorough outline of those changes is [here](https://github.com/hexops/mach/issues/1135#issuecomment-1891175749), but specifically the changes that needed to be made in this project are:

- `var` -> `const` as it's now a compile-time requirement for data that's not mutated
- Upgrading`build.zig to latest constructs
- Adding the `paths` field to build.zig.zon

Note: I converted to a draft b/c I only tested with one example. Doing the rest now

### CODE REVIEW

**Comment by jcalabro** [comment]
Oops, missed the note in the README about the [0.12.0 branch](https://github.com/zigzap/hello-0.12.0). Will close, but if you need any help with those changes, feel free to use, or ping me and I can make the changes over there. Sorry for the noise!

**Comment by renerocksai** [comment]
Hi there and thanks for all the work in this PR. Have you checked the readme? Zap is intentionally made for the current stable release of zig (0.11). That's a feature.

However, since many users seem to prefer to use zig master, there is a zig-0.12.0 branch for zap.

**Comment by jcalabro** [comment]
Hah, jinx! Thanks, sorry again!

**Comment by renerocksai** [comment]
No worries and many thanks for the offer 👍!

**Pull request closed without merging**
