### PR TITLE
add macos and windows to CI

### PR DESCRIPTION
**Pull request by mattnite**

### CODE REVIEW

**Comment by renerocksai** [comment]
Thx! Have you actually tried Windows builds? I was under the impression that they don't work because of facil.io...

**Comment by mattnite** [comment]
I pushed this to see if it would succeed :) it failed crosscompilation on my machine, but maybe it works natively on windows.

**Comment by renerocksai** [comment]
Fair enough, let's find out; yolo 😄

**Comment by renerocksai** [comment]
OK, Win didn't like it for two reasons. First, `build_all.sh` is a bit too shelly for windows. Second, when building the tests, it couldn't find essential header files.

Bo, the author of facil.io, pointed me to [his 0.8.x repo](https://github.com/facil-io/cstl) which is C only and apparently supports Windows. So there is Windows hope for the future.

I'll add macos to the matrix. Or, merge your PR and remove Windows from the CI.

**Pull request merged**
